font_family GeistMono Nerd Font
font_size

disable_ligatures yes
enable_audio_bell no

# shell zsh
# shell_integration no-cursor

cursor_shape block
# url_color #e8eaed
url_style curly

remember_window_size no
# initial_window_width 640
# initial_window_height 400
initial_window_width 78c
initial_window_height 23c
window_padding_width 30
cursor_blink_interval 0

background_opacity 0.50
confirm_os_window_close 0

# performance settings
sync_to_monitor no


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME